# Generated by Django 3.0.1 on 2020-06-17 14:31

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_id', models.IntegerField(default=0, unique=True)),
                ('pkmn_name', models.CharField(max_length=25, unique=True)),
                ('is_legendary', models.BinaryField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=api_app.models.pokemon.photo_upload_path)),
            ],
        ),
    ]
