# Generated by Django 3.0.1 on 2020-06-17 05:14

import api_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api_app.models.pokemon.photo_upload_path),
        ),
    ]
