# Generated by Django 3.0.1 on 2020-06-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20200619_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='moves',
            name='accuracy',
            field=models.IntegerField(default=100),
        ),
    ]
